name: GoogleAntiGrief
main: GoogleAntiGrief.MainClass
version: 0.02
author: TheFloatGoat
commands:
  vet:
    description: This command uses google to vet users.
    usage: "Usage: /vet [name] {keywords}"
